# Generated by Django 3.1.7 on 2021-02-24 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='receipt image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFileTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, verbose_name='tag key')),
                ('value', models.TextField(null=True, verbose_name='tag value')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.mediafile', verbose_name='media file')),
            ],
        ),
    ]
