# Generated by Django 3.1.7 on 2021-02-25 18:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210224_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to=core.models.make_file_path, verbose_name='file'),
        ),
    ]
