# Generated by Django 3.1.7 on 2021-03-06 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(db_index=True, unique=True, verbose_name='website')),
                ('config', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='section id')),
            ],
        ),
        migrations.CreateModel(
            name='ContentVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='content.contentsection', verbose_name='section')),
            ],
        ),
    ]
