# Generated by Django 3.1.7 on 2021-03-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsection',
            name='slot',
            field=models.CharField(choices=[('meta', 'meta'), ('header', 'header'), ('body', 'body'), ('footer', 'footer')], db_index=True, default='body', max_length=16, verbose_name='slot'),
        ),
        migrations.AlterField(
            model_name='contentconfiguration',
            name='key',
            field=models.TextField(db_index=True, unique=True, verbose_name='key'),
        ),
    ]
