# Generated by Django 3.1.7 on 2021-03-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210308_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(db_index=True, max_length=24, unique=True, verbose_name='domain name')),
                ('display_name', models.CharField(max_length=24, verbose_name='display name')),
            ],
        ),
        migrations.AddField(
            model_name='contentsection',
            name='group',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='group'),
        ),
        migrations.AddField(
            model_name='contentsection',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='name',
            field=models.CharField(db_index=True, max_length=24, unique=True, verbose_name='section id'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='slot',
            field=models.CharField(choices=[('body', 'body'), ('meta', 'meta'), ('header', 'header'), ('footer', 'footer')], db_index=True, default='body', max_length=24, verbose_name='slot'),
        ),
    ]
